import { Badge } from "../types";

const PLACEHOLDER_IMAGE =
  "https://raw.githubusercontent.com/alma-labs/hydrex-lists/main/assets/badges/placeholder.png";

export const Badges: Badge[] = [
  {
    name: "Hydrex O.G.",
    nftId: "0",
    image: PLACEHOLDER_IMAGE,
    rewardImage: PLACEHOLDER_IMAGE,
    description:
      "A Badge designed for all the Hydrex O.G.'s and day 1 supporters.",
    type: "Activity",
    partnerName: "Hydrex",
    minHydropoints: 0,
    poolSize: 10000,
    maxSupply: 10000,
  },
  {
    name: "Base Starter",
    nftId: "1",
    image: PLACEHOLDER_IMAGE,
    rewardImage: PLACEHOLDER_IMAGE,
    description:
      "Provide liquidity to acquire 1000+ Hydropoints & become a tier 1 Based Hydrex Member.",
    type: "Tier",
    partnerName: "Base",
    minHydropoints: 1000,
    poolSize: 10000,
  },
  {
    name: "Honest Work",
    nftId: "2",
    image: PLACEHOLDER_IMAGE,
    rewardImage: PLACEHOLDER_IMAGE,
    description:
      "Provide liquidity to acquire 10,000+ Hydropoints & become a tier 2 Based Hydrex Member.",
    type: "Tier",
    partnerName: "Base",
    minHydropoints: 10000,
    poolSize: 10000,
  },
  {
    name: "DeFi Degen",
    nftId: "3",
    image: PLACEHOLDER_IMAGE,
    rewardImage: PLACEHOLDER_IMAGE,
    description:
      "Provide liquidity to acquire 100,000+ Hydropoints & become a tier 3 Based Hydrex Member.",
    type: "Tier",
    partnerName: "Base",
    minHydropoints: 100000,
    poolSize: 10000,
  },
  {
    name: "Master Baser",
    nftId: "4",
    image: PLACEHOLDER_IMAGE,
    rewardImage: PLACEHOLDER_IMAGE,
    description:
      "Provide liquidity to acquire 1,000,000+ Hydropoints & become a tier 4 Based Hydrex Member.",
    type: "Tier",
    partnerName: "Base",
    minHydropoints: 1000000,
    poolSize: 20000,
  },
  {
    name: "Based God",
    nftId: "5",
    image: PLACEHOLDER_IMAGE,
    rewardImage: PLACEHOLDER_IMAGE,
    description:
      "Provide liquidity to acquire 10,000,000+ Hydropoints & become the top Tier Based Hydrex Member.",
    type: "Tier",
    partnerName: "Base",
    minHydropoints: 10000000,
    poolSize: 30000,
  },
  {
    name: "Purple App",
    nftId: "6",
    image: PLACEHOLDER_IMAGE,
    rewardImage: PLACEHOLDER_IMAGE,
    description:
      "Create a Farcaster account & use it for Protocol Mining to claim this badge.",
    type: "Activity",
    partnerName: "Farcaster",
    minHydropoints: 100,
    poolSize: 5000,
    maxSupply: 1000,
  },
  {
    name: "Caster Pro",
    nftId: "7",
    image: PLACEHOLDER_IMAGE,
    rewardImage: PLACEHOLDER_IMAGE,
    description:
      "Register your Farcaster account as a Pro user & participate in Protocol Mining to claim this badge.",
    type: "Activity",
    partnerName: "Farcaster",
    minHydropoints: 100,
    poolSize: 1500,
    maxSupply: 100,
  },
  {
    name: "Squad Up",
    nftId: "8",
    image: PLACEHOLDER_IMAGE,
    rewardImage: PLACEHOLDER_IMAGE,
    description:
      "Follow @HydrexFi on Farcaster and claim this with your Farcaster associated account.",
    type: "Activity",
    partnerName: "Farcaster",
    minHydropoints: 10,
    poolSize: 5000,
    maxSupply: 5000,
  },
  {
    name: "Base Dot ETH",
    nftId: "9",
    image: PLACEHOLDER_IMAGE,
    rewardImage: PLACEHOLDER_IMAGE,
    description:
      "Claim this Badge with an account that has a Basename associated.",
    type: "Activity",
    partnerName: "Base",
    minHydropoints: 10,
    poolSize: 10000,
    maxSupply: 5000,
  },
  {
    name: "Pretty Smart",
    nftId: "10",
    image: PLACEHOLDER_IMAGE,
    rewardImage: PLACEHOLDER_IMAGE,
    description: "Claim this Badge with an account that is a Smart Wallet.",
    type: "Activity",
    partnerName: "Base",
    minHydropoints: 10,
    poolSize: 10000,
    maxSupply: 2500,
  },
  {
    name: "It's Official",
    nftId: "11",
    image: PLACEHOLDER_IMAGE,
    rewardImage: PLACEHOLDER_IMAGE,
    description:
      "Claim this Badge with an account that has an onchain Coinbase Verification Attestation.",
    type: "Activity",
    partnerName: "Base",
    minHydropoints: 100,
    poolSize: 10000,
    maxSupply: 500,
  },
  {
    name: "Morphite",
    nftId: "12",
    image: PLACEHOLDER_IMAGE,
    rewardImage: PLACEHOLDER_IMAGE,
    description:
      "Claim this Badge with an account that has a deposit over $100 on Morpho.",
    type: "Activity",
    partnerName: "Base",
    minHydropoints: 1000,
    poolSize: 2500,
    maxSupply: 250,
  },
  {
    name: "Buildooor",
    nftId: "13",
    image: PLACEHOLDER_IMAGE,
    rewardImage: PLACEHOLDER_IMAGE,
    description:
      "Claim this Badge with an account that has deployed a contract on Base.",
    type: "Activity",
    partnerName: "Base",
    minHydropoints: 1000,
    poolSize: 2500,
    maxSupply: 250,
  },
  {
    name: "Content Coiner",
    nftId: "14",
    image: PLACEHOLDER_IMAGE,
    rewardImage: PLACEHOLDER_IMAGE,
    description:
      "Claim this Badge with an account that has coined content on Zora.",
    type: "Activity",
    partnerName: "Base",
    minHydropoints: 1000,
    poolSize: 2500,
    maxSupply: 250,
  },
  {
    name: "Mother Flauncher",
    nftId: "15",
    image: PLACEHOLDER_IMAGE,
    rewardImage: PLACEHOLDER_IMAGE,
    description: "Claim this Badge with an account that has flaunched a token.",
    type: "Activity",
    partnerName: "Base",
    minHydropoints: 1000,
    poolSize: 2500,
    maxSupply: 250,
  },
];
