import { Badge } from "../types";

const LINK_PREFIX =
  "https://raw.githubusercontent.com/alma-labs/hydrex-lists/main/assets/badges";

const Badges: Badge[] = [
  {
    name: "Hydrex O.G.",
    nftId: "0",
    image: `${LINK_PREFIX}/0.png`,
    rewardImage: `${LINK_PREFIX}/0.png`,
    description: "For Hydrex Day 1 supporters",
    fullDescription:
      "A Badge designed for all the Hydrex O.G.'s and day 1 supporters. Available for minting by anyone early enough.",
    type: "Activity",
    category: "Tier",
    partnerName: "Hydrex",
    minHydropoints: 0,
    poolSize: 10000,
    maxSupply: 10000,
  },
  {
    name: "Purple App",
    nftId: "6",
    image: `${LINK_PREFIX}/6.png`,
    rewardImage: `${LINK_PREFIX}/6.png`,
    description: "For the Mini App Users",
    fullDescription:
      "User a Farcaster account that has accumulated sufficient Hydropoints to claim this badge.",
    type: "Activity",
    category: "Social",
    partnerName: "Farcaster",
    minHydropoints: 100,
    poolSize: 5000,
    maxSupply: 1000,
  },
  {
    name: "Content Coiner",
    nftId: "13",
    image: `${LINK_PREFIX}/13.png`,
    rewardImage: `${LINK_PREFIX}/13.png`,
    description: "Coin Content on Zora Uni V4",
    fullDescription:
      "Claim this Badge with an account that has coined content on Zora.",
    type: "Activity",
    category: "Based",
    partnerName: "Base",
    minHydropoints: 1000,
    poolSize: 2500,
    maxSupply: 250,
  },
  {
    name: "Mother Flauncher",
    nftId: "14",
    image: `${LINK_PREFIX}/14.png`,
    rewardImage: `${LINK_PREFIX}/14.png`,
    description: "Flaunch a Token on Base",
    fullDescription:
      "Claim this Badge with an account that has flaunched a token.",
    type: "Partner",
    category: "Memes",
    partnerName: "Base",
    minHydropoints: 1000,
    poolSize: 2500,
    maxSupply: 250,
  },
  {
    name: "Caster Pro",
    nftId: "7",
    image: `${LINK_PREFIX}/7.png`,
    rewardImage: `${LINK_PREFIX}/7.png`,
    description: "Become a Farcaster Pro Subscriber",
    fullDescription:
      "Register your Farcaster account as a Pro user & participate in Protocol Mining to claim this badge.",
    type: "Activity",
    category: "Social",
    partnerName: "Farcaster",
    minHydropoints: 100,
    poolSize: 1500,
    maxSupply: 100,
  },
  {
    name: "Squad Up",
    nftId: "8",
    image: `${LINK_PREFIX}/8.png`,
    rewardImage: `${LINK_PREFIX}/8.png`,
    description: "Become an Farcaster Hydrex Follower",
    fullDescription:
      "Follow @HydrexFi on Farcaster and claim this with your Farcaster associated account.",
    type: "Activity",
    category: "Social",
    partnerName: "Farcaster",
    minHydropoints: 10,
    poolSize: 5000,
    maxSupply: 5000,
  },
  {
    name: "Base Dot ETH",
    nftId: "9",
    image: `${LINK_PREFIX}/9.png`,
    rewardImage: `${LINK_PREFIX}/9.png`,
    description: "For the Basename Hodlers",
    fullDescription:
      "Claim this Badge with an account that has a Basename associated.",
    type: "Activity",
    category: "Based",
    partnerName: "Base",
    minHydropoints: 10,
    poolSize: 10000,
    maxSupply: 5000,
  },
  {
    name: "Pretty Smart",
    nftId: "10",
    image: `${LINK_PREFIX}/10.png`,
    rewardImage: `${LINK_PREFIX}/10.png`,
    description: "Only for Smart Wallet Users",
    fullDescription: "Claim this Badge with an account that is a Smart Wallet.",
    type: "Activity",
    category: "Based",
    partnerName: "Base",
    minHydropoints: 10,
    poolSize: 10000,
    maxSupply: 2500,
  },
  {
    name: "It's Official",
    nftId: "11",
    image: `${LINK_PREFIX}/11.png`,
    rewardImage: `${LINK_PREFIX}/11.png`,
    description: "Onchain Coinbase Verified Users",
    fullDescription:
      "Claim this Badge with an account that has an onchain Coinbase Verification Attestation.",
    type: "Activity",
    category: "Based",
    partnerName: "Base",
    minHydropoints: 100,
    poolSize: 10000,
    maxSupply: 500,
  },
  {
    name: "Buildooor",
    nftId: "12",
    image: `${LINK_PREFIX}/12.png`,
    rewardImage: `${LINK_PREFIX}/12.png`,
    description: "Deploy a Contract on Base",
    fullDescription:
      "Claim this Badge with an account that has deployed a contract on Base.",
    type: "Activity",
    category: "Based",
    partnerName: "Base",
    minHydropoints: 1000,
    poolSize: 2500,
    maxSupply: 250,
  },
  {
    name: "You The One",
    nftId: "15",
    image: `${LINK_PREFIX}/15.png`,
    rewardImage: `${LINK_PREFIX}/15.png`,
    description: "Coinbase One Member Onchain Attestation",
    fullDescription:
      "Claim this Badge with an account that has a Coinbase One Membership.",
    type: "Activity",
    category: "Based",
    partnerName: "Base",
    minHydropoints: 1000,
    poolSize: 2500,
    maxSupply: 100,
  },
  {
    name: "Base Starter",
    nftId: "1",
    image: `${LINK_PREFIX}/1.png`,
    rewardImage: `${LINK_PREFIX}/1.png`,
    description: "First Tier Hydrex Member",
    fullDescription:
      "Provide liquidity to acquire 1000+ Hydropoints & become a tier 1 Based Hydrex Member.",
    type: "Tier",
    category: "Tier",
    partnerName: "Base",
    minHydropoints: 1000,
    poolSize: 10000,
  },
  {
    name: "Honest Work",
    nftId: "2",
    image: `${LINK_PREFIX}/2.png`,
    rewardImage: `${LINK_PREFIX}/2.png`,
    description: "Tier 2 Hydrex Member",
    fullDescription:
      "Provide liquidity to acquire 10,000+ Hydropoints & become a tier 2 Based Hydrex Member.",
    type: "Tier",
    category: "Tier",
    partnerName: "Base",
    minHydropoints: 10000,
    poolSize: 10000,
  },
  {
    name: "DeFi Degen",
    nftId: "3",
    image: `${LINK_PREFIX}/3.png`,
    rewardImage: `${LINK_PREFIX}/3.png`,
    description: "Tier 3 Hydrex Member",
    fullDescription:
      "Provide liquidity to acquire 100,000+ Hydropoints & become a tier 3 Based Hydrex Member.",
    type: "Tier",
    category: "Tier",
    partnerName: "Base",
    minHydropoints: 100000,
    poolSize: 10000,
  },
  {
    name: "Master Baser",
    nftId: "4",
    image: `${LINK_PREFIX}/4.png`,
    rewardImage: `${LINK_PREFIX}/4.png`,
    description: "Tier 4 Hydrex Member",
    fullDescription:
      "Provide liquidity to acquire 1,000,000+ Hydropoints & become a tier 4 Based Hydrex Member.",
    type: "Tier",
    category: "Tier",
    partnerName: "Base",
    minHydropoints: 1000000,
    poolSize: 20000,
  },
  {
    name: "Based God",
    nftId: "5",
    image: `${LINK_PREFIX}/5.png`,
    rewardImage: `${LINK_PREFIX}/5.png`,
    description: "Top Tier Hydrex Member",
    fullDescription:
      "Provide liquidity to acquire 10,000,000+ Hydropoints & become the top Tier Based Hydrex Member.",
    type: "Tier",
    category: "Tier",
    partnerName: "Base",
    minHydropoints: 10000000,
    poolSize: 30000,
  },
];

export { Badges };
